<%@ Page Title="Schedule Venue Details" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="SchduleVenueDetails.aspx.cs" Inherits="KIPOINT.SchduleVenueDetails" %>
<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">

    <style>

       table {
            border-collapse: collapse;
            border-spacing: 0;
        }

        td,
        th {
            padding: 2px;
           
        }

        .status {
            font-size:40px;
            padding: 5px;
        }

        .auto-style1 {
            height: 22px;
        }

        .auto-style2 {
            height: 24px;
            width: 676px;
        }

    </style>
    <br />
    

    

 <div class="card pb-3">
     <div class="container-fluid">
               <div class="modal-content">  
                   <div class="modal-header" style="background:#666666; padding: 0px;">
                       <h1 class="status">&nbsp;<asp:Label ID="lbl_status" runat="server" Text="Approved" Height="50px" Width="500px" Font-Italic="True"></asp:Label></h1>
                   </div>
                    <div class="modal-body">
                      <table align="center" class="auto-style2">
                        <tr>
                            <td class="auto-style1">
                                REQ</td>
                            <td class="auto-style1">
                                <asp:TextBox ID="txt_req" runat="server" Height="25px" Width="200px" Enabled="False"></asp:TextBox>
                            </td>
                            <td rowspan="10">
                                <br />
         <asp:UpdatePanel ID="AddEquipmentPanel" runat="server">
                    <ContentTemplate>  
                     <asp:DropDownList ID="DrpEquipment" runat="server" Height="30px" Width="200px"></asp:DropDownList>
                     <asp:Button ID="btn_Add_Equipemt" runat="server" Text="Add" class="btn btn-primary" OnClick="btn_Add_Equipemt_Click" />
                                <br />

                 
                    <asp:GridView ID="reserve_list" runat="server" DataKeyNames="id" 
                    OnRowDeleting="OnRowDeleting" EmptyDataText="No records has been added."
                    ShowHeaderWhenEmpty="True" Width="120%" Height="100px" HorizontalAlign="Center" AutoGenerateColumns="False" BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" GridLines="Horizontal" AutoGenerateDeleteButton="True" >
                    <Columns>

                        <asp:TemplateField HeaderText="Equipment">
                             <ItemTemplate>
                                <asp:Label ID="lbl_equip" runat="server" Text='<% #Eval("eq_name") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                         <asp:TemplateField HeaderText="Number">
                             <ItemTemplate>
                                <asp:Label ID="lbl_equipnum" runat="server" Text='<% #Eval("eq_num") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>

                          <asp:TemplateField HeaderText="Brand">
                             <ItemTemplate>
                                <asp:Label ID="lbl_brand" runat="server" Text='<% #Eval("eq_brand") %>'></asp:Label>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
                    <HeaderStyle BackColor="#333333" ForeColor="White" HorizontalAlign="Left" VerticalAlign="Middle" Font-Bold="True" />
                    <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
                    <RowStyle HorizontalAlign="Left" VerticalAlign="Middle" />
                    <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F7F7F7" />
                    <SortedAscendingHeaderStyle BackColor="#4B4B4B" />
                    <SortedDescendingCellStyle BackColor="#E5E5E5" />
                    <SortedDescendingHeaderStyle BackColor="#242121" />
                    </asp:GridView>

                                <asp:TextBox ID="txt_reserverid" runat="server" Height="25px" Width="200px" Enabled="False" Visible="False"></asp:TextBox>

                                <asp:TextBox ID="txt_id" runat="server" Enabled="False" Visible="False"></asp:TextBox>

                                <asp:Label ID="Label1" runat="server"></asp:Label>
            
                    </ContentTemplate>
                    </asp:UpdatePanel> 

                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">
                                Venue Name</td>
                            <td style="height: 22px">
                                <asp:TextBox ID="txt_venue" runat="server" Height="25px" Width="200px" Enabled="False"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">
                                Purpose</td>
                            <td class="auto-style1">
                                <asp:TextBox ID="txt_purpose" runat="server" Height="87px" Width="200px" Enabled="False" TextMode="MultiLine"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">
                                Date start</td>
                            
                                <td><asp:TextBox ID="txt_datestart" runat="server" Height="25px" Width="200px" TextMode="Date" Enabled="False"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">
                                Date end</td>
                            
                                <td><asp:TextBox ID="txt_dateend" runat="server" Height="25px" Width="200px" TextMode="Date" Enabled="False"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">
                                Time start</td>
                            
                                <td><asp:TextBox ID="txt_timestart" runat="server" Height="25px" Width="200px" TextMode="Time" Enabled="False"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">
                                Time end</td>
                            
                                <td><asp:TextBox ID="txt_timeend" runat="server" Height="25px" Width="200px" TextMode="Time" Enabled="False"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">
                                Reserved by</td>
                            <td style="height: 22px">
                                <asp:TextBox ID="txt_reserve" runat="server" Height="25px" Width="200px" Enabled="False"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1">
                                Remarks</td>
                            <td style="height: 22px">
                                <asp:TextBox ID="txt_remarks" runat="server" Height="102px" Width="200px" Enabled="False" TextMode="MultiLine"></asp:TextBox>
                            </td>
                        </tr>
                        <tr>
                            <td class="auto-style1" colspan="2">
                                &nbsp;</td>
                        </tr>
                        </table>

                        
                    </div>
   
                        <div class="modal-footer">    
                                <asp:Button ID="btn_approve" runat="server" Text="Approved" class="btn btn-success" OnClick="btn_approve_Click" />                    
                                <asp:Button ID="btn_disapprove" runat="server" Text="Disaproved" class="btn btn-danger" OnClick="btn_disapprove_Click" />
                                <asp:Button ID="btn_reschedule" runat="server" Text="Reschedule" class="btn btn-info" OnClick="btn_reschedule_Click" />  
                        </div>
                   </div>                   
              
     </div>
</div>


</asp:Content>
